name: End-to-End tests
on: [push, pull_request]
env:
        BROWSERSTACK_ACCESS_KEY: "${{ secrets.BROWSERSTACK_ACCESS_KEY }}"
        BROWSERSTACK_USERNAME: "${{ secrets.BROWSERSTACK_USERNAME }}"
        PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}" 
jobs:
  build:
    name: Run Tests Across Node.js Versions and Operating Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [8, 10, 12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      
      - shell: pwsh
        run: $Env:PERCY_TOKEN="${{ secrets.PERCY_TOKEN }}"
      
      - name: Run TestCafe tests
        run: npm run test