name: End-to-End tests
on: [push, pull_request]
env:
        BROWSERSTACK_ACCESS_KEY: "${{ secrets.BROWSERSTACK_ACCESS_KEY }}"
        BROWSERSTACK_USERNAME: "${{ secrets.BROWSERSTACK_USERNAME }}"
jobs:
  test:
    name: Run TestCafe tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1

      - name: 'Building web application to be tested'
        run: npm install
      
      - shell: pwsh
        env: 
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
        run: $Env:PERCY_TOKEN"

      - name: Run TestCafe tests
        run: npm run test