name: End-to-End tests
on: [push]
env:
        BROWSERSTACK_ACCESS_KEY: "${{ secrets.BROWSERSTACK_ACCESS_KEY }}"
        BROWSERSTACK_USERNAME: "${{ secrets.BROWSERSTACK_USERNAME }}"
jobs:
  test:
    name: Run TestCafe tests
    runs-on: windows-latest
     steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Run tests
        uses: marialbert/testcafe-action@latest
        with:
            args: "chrome tests"